import type { GetServerSideProps, Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { resetServerContext } from "react-beautiful-dnd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello",
  description: "Generated by Sony",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/**Header */}
     
      {/**Board */}

      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
}


