import type { GetServerSideProps, Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { resetServerContext } from "react-beautiful-dnd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hurun India Beta",
  description: "Generated by Sony",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" sizes="32x32" href="/favicon-32x32.png"></link>
        <link rel="icon" sizes="16x16" href="/favicon-16x16.png"></link>
      </head>
      {/**Header */}
     
      {/**Board */}

      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
}


